### ISSUE TITLE
ValueError: bg_num_rois = 0 and fg_num_rois = 0, this should not happen!

### ISSUE THREAD

**Issue by artuncF** [jwyang/faster-rcnn.pytorch#111]
When I tried to train the network with my own dataset which is actually https://github.com/udacity/self-driving-car/tree/master/annotations, this problem occurs after 900 iterations in the first epoch. Can you point out the  source of problem?

**Comment by artuncF** [comment]
I should also mention that the repo is up-to-date, I show the commit related the same error but it didn't solve the problem.

**Comment by artuncF** [comment]
Your commit didn't solve the problem.

**Comment by WillSuen** [comment]
I have same issue on pascal_voc_0712 data set (at 5000 iter of epoch 1) after I try to implement R-FCN with this repo. Any one know what is a possible reason?

**Comment by jwyang** [comment]
Hi, @WillSuen are you using the most recent code?

**Comment by WillSuen** [comment]
@jwyang Yes, I just tried with the most recent code, but still got the same issue. The training process goes well, with loss decreasing each iter, and then at 5000 iter comes this `ValueError: bg_num_rois = 0 and fg_num_rois = 0, this should not happen!`

**Comment by WillSuen** [comment]
I have changed several parameters in cfg, 
```
           'RPN_MIN_SIZE': 8, -> 0
           'RPN_POST_NMS_TOP_N': 2000, -> 300
           'RPN_PRE_NMS_TOP_N': 12000, -> 6000
```
Will these parameters be the reason? I'll change them back to see what happens

**Comment by WillSuen** [comment]
I finally fix this error I met, it is because I changed the directory of configure.py file so the program used wrong pkl file when loading data set. Hope this might help you.

**Comment by artuncF** [comment]
I figured out that rpn_loss_box and rpn_class_box are returning nan, have you any idea why is that happening? @jwyang

**Comment by artuncF** [comment]
And I am pretty sure about my ground truth boxes are true, I think there is  a problem with rois and rpn.

**Comment by jwyang** [comment]
@artuncF I thought the new commit already solved this issue, but it turns out not. I will check again.

**Comment by CodeJjang** [comment]
Try verifying that `MAX_NUM_GT_BOXES` parameter matches to your dataset - I had to calculate it on my dataset and then set it to the correct number. It's one of the small things that helped me to train. Update us if it helped you or not

**Comment by ahmed-shariff** [comment]
@artuncF tried lowering the learning rate?
also something that I missed when training on my own dataset: remember to have the 0th index represent the background.

**Comment by artuncF** [comment]
I solved the problem. The problem is related to my annotation files now network working accurately.

**Comment by Frostinassiky** [comment]
I met the same problem. Simply we can skip that batch.

**Comment by wwtalwtaw** [comment]
@jwyang Hi, I met this bug when training on the coco2017, and I find it was caused by a bug in [roibatchLoader.py](https://github.com/jwyang/faster-rcnn.pytorch/blob/28db6d0b313220d200b739f4e22410fbe35529f4/lib/roi_data_layer/roibatchLoader.py#L145).

To keep the same ratio of images within the same batch, You crop them randomly through this block of code. However, when the picture is too long and objects are nearby the edge of the image, it is prone to crop the objects and thus the number of bounding boxes becomes zero. Here I give an example:

Before the cropping:
![image](https://user-images.githubusercontent.com/11582122/42919451-7de35c06-8b44-11e8-84fa-94d2467e5745.png)

After:
![image](https://user-images.githubusercontent.com/11582122/42919467-8e8df994-8b44-11e8-93a1-ae1888e78c5c.png)

Because the cropping is random, simply skipping such batch is a good idea.

**Comment by kentaroy47** [comment]
cleaning up the data/cache files helped me on this..

**Comment by mehrdadazizi72** [comment]
I have same issue when training on own dataset
Cleaning data/cache also didn't help

**Comment by mehrdadazizi72** [comment]
> I solved the problem. The problem is related to my annotation files now network working accurately.

What's your annotations problem?

**Comment by marcunzueta** [comment]
check #594
