### ISSUE TITLE
RuntimeError: reciprocal is not implemented for type torch.cuda.LongTensor

### ISSUE THREAD

**Issue by ArchieGu** [jwyang/faster-rcnn.pytorch#147]
I saw someone posted a similar problem #116 

Does this have something to do with Pytorch version???

Anyone with solution, plz contact me, thank you.

**Comment by LiuHao-THU** [comment]
I also met this problem when I try to compile with pytorch 0.4.0? how to solve this problem? while i do not want to change the version of my pytorch...

**Comment by xylcbd** [comment]
modify faster-rcnn.pytorch\lib\model\rpn\anchor_target_layer.py +156, from

`num_examples = torch.sum(labels[i] >= 0)`

to

`num_examples = torch.sum(labels[i] >= 0).item()`

**Comment by xylcbd** [comment]
another issue can be resoved with modify faster-rcnn.pytorch\lib\model\rpn\proposal_target_layer_cascade.py +133, from

`labels = gt_boxes[:,:,4].contiguous().view(-1).index(offset.view(-1))\
                                                            .view(batch_size, -1)`

to 

`labels = gt_boxes[:,:,4].contiguous().view(-1).index((offset.view(-1), ))\
                                                            .view(batch_size, -1)`

**Comment by D-X-Y** [comment]
https://github.com/pytorch/pytorch/issues/2772

**Comment by yjump** [comment]
Hi @xylcbd, thank you for your solution. But I meet with anothor issue caused by:

Traceback (most recent call last):
  File "trainval_net.py", line 332, in <module>
    clip_gradient(fasterRCNN, 10.)
  File "/home/yanjp/faster-rcnn.pytorch/lib/model/utils/net_utils.py", line 52, in clip_gradient
    p.grad.mul_(norm)
RuntimeError: Expected object of type torch.cuda.FloatTensor but found type torch.FloatTensor for argument #3 'other'
Exception NameError: "global name 'FileNotFoundError' is not defined" in <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7f75f997dd50>> ignored

I try to add norm.cuda() to solve it, but failed as:

Traceback (most recent call last):
  File "trainval_net.py", line 332, in <module>
    clip_gradient(fasterRCNN, 10.)
  File "/home/yanjp/faster-rcnn.pytorch/lib/model/utils/net_utils.py", line 51, in clip_gradient
    norm = norm.cuda()
AttributeError: 'float' object has no attribute 'cuda'
Exception NameError: "global name 'FileNotFoundError' is not defined" in <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7f1460182cd0>> ignored

could you kindly offer some advices? Thanks a lot!

**Comment by xylcbd** [comment]
@jwyang, maybe you should check the input parameter "clip_norm", is it hosted by CUDA?

**Comment by wtliao** [comment]
@xylcbd thanks so much for your solution. It works for me now

**Comment by isalirezag** [comment]
@yjump where did you put it exactly? can you please see if i put it in the right position?:
```
    norm = clip_norm / max(totalnorm, clip_norm)
    for p in model.parameters():
        if p.requires_grad:
            p.grad.mul_(norm)
            norm = torch.tensor([norm],device='cuda')
```

**Comment by yjump** [comment]
@isalirezag put it before p.grad.mul_(norm) as gradiants are calculated on GPU

**Comment by 1csu** [comment]
Hi @xylcbd, thank you for your solutions. But I meet with anothor issue caused by:
File "/media/csu/新加卷/AI Competition/Baidu Competition/intermediary_contest/faster-rcnn.pytorch-master/trainval_net.py", line 316, in <module>
    loss.backward()
  File "/home/csu/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/csu/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 89, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/media/csu/新加卷/AI Competition/Baidu Competition/intermediary_contest/faster-rcnn.pytorch-master/lib/model/roi_align/functions/roi_align.py", line 38, in backward
    assert(self.feature_size is not None and grad_output.is_cuda)
AssertionError
Could you offer me some advice?Thanks a lot

**Comment by kurosaki-fish** [comment]
@1csu I also met this problem, have you solved this problem?

**Comment by 1csu** [comment]
@kurosaki-fish ,no,have you solved the problem?

**Comment by changjo** [comment]
For me, changing
```
totalnorm = np.sqrt(totalnorm) 
```
to
```
totalnorm = torch.sqrt(totalnorm)
```

Solved this problem `RuntimeError: Expected object of type torch.cuda.FloatTensor but found type torch.FloatTensor`...

**Comment by Daniellllzzh** [comment]
command:python trainval_net.py --cuda
Solved the problem: AssertionError

**Comment by jwyang** [comment]
the current master supports pytorch 0.4.0 now, feel free to use it!

**Comment by ssli23** [comment]
> I also met this problem when I try to compile with pytorch 0.4.0? how to solve this problem? while i do not want to change the version of my pytorch
Have you solved your problem?
