### ISSUE TITLE
Why write custom cuda instead of use autograd?

### ISSUE THREAD

**Issue by yxchng** [jwyang/faster-rcnn.pytorch#252]
is autograd much slower than writing backward yourself with cuda code?

**Comment by jwyang** [comment]
@yxchng i did not compare but i do not think there are much gap between these two. Since what the autograd does is recording the computational graph in the forward pass, and then call the derivative computation according to the graph path. Basically, to get the gradient, it will call all the backward function in each of the module in the graph. So I do not see much difference between these two.
