### ISSUE TITLE
error while running test_net.py

### ISSUE THREAD

**Issue by water2bear** [jwyang/faster-rcnn.pytorch#268]
while running test_net.py on my own dataset it throws the following error
### **load checkpoint /home/.../models/vgg16/pascal_voc/faster_rcnn_1_1_10021.pth
While copying the parameter named RCNN_cls_score.weight, whose dimensions in the                                    model are torch.Size([2, 4096]) and whose dimensions in the checkpoint are torc                                   h.Size([21, 4096]), ...
Traceback (most recent call last):
  File "test_net.py", line 170, in <module>
    fasterRCNN.load_state_dict(checkpoint['model'])
  File "/usr/share/Anaconda2/lib/python2.7/site-packages/torch/nn/modules/module                                   .py", line 360, in load_state_dict
    own_state[name].copy_(param)
RuntimeError: invalid argument 2: sizes do not match at /pytorch/torch/lib/THC/g                                   eneric/THCTensorCopy.c:95**
Can you help me solve this issure?

**Comment by Chumbyte** [comment]
had a similar error that was fixed in this comment, https://github.com/jwyang/faster-rcnn.pytorch/issues/155#issuecomment-401600087

21 is the number of classes (20 classes + '__background__'), it seems for some reason your saved model only has 2 classes (as RCNN_cls_score.weight has dimension torch.Size([2, 4096]))

hopefully that helps
