### ISSUE TITLE
Testing the model with batch_size>1

### ISSUE THREAD

**Issue by LamontQiao** [jwyang/faster-rcnn.pytorch#29]
Hi, @jwyang 

When I test the model with batch_size>1 (--bs 16), I got the **RuntimeError** in test_net.py:

    Traceback (most recent call last):  
    
    File "test_net.py", line 234, in <module>
        
        pred_boxes = bbox_transform_inv(boxes, box_deltas, 1)
    
    File "/home/faster-rcnn.pytorch/lib/model/rpn/bbox_transform.py", line 93, in bbox_transform_inv
        
        pred_ctr_x = dx * widths.unsqueeze(2) + ctr_x.unsqueeze(2)
    
    File "/home/Library/anaconda2/lib/python2.7/site-packages/torch/tensor.py", line 309, in __mul__
        
        return self.mul(other)

    RuntimeError: invalid argument 3: sizes do not match at /opt/conda/conda-bld/pytorch_1502006348621/work/torch/lib/THC/generated/../generic/THCTensorMathPointwise.cu:297

so, what can i do to support mGPUs & batch_size in test_net.py? 

Thanks a lot. : )

**Comment by Rizhiy** [comment]
@jwyang I think multi-batch test should be added by default to the repo as you can generally fit more images on a GPU during a test. Therefore this would greatly speed up test and validation if you choose to use it later.

**Comment by Cadene** [comment]
@Rizhiy Could you add it to the repo?

Beware, the collate function to stack several items (images and gt_boxes) should be different from the one in the training pass. In fact, during the training, items from the same batch are resized, cropped and padded to fit in the same tensors. During the testing, items from the same batch should only be padded. Even by doing so, the output of one item could depend on the other items belonging to its batch (because of the padding).

**Comment by Rizhiy** [comment]
@Cadene Yeah, I was thinking of just padding them together. Will try to add it tomorrow.

**Comment by Rizhiy** [comment]
I managed to get this working on my dataset, [here](https://github.com/Rizhiy/faster-rcnn.pytorch/tree/multi-batch-test) is the branch.
Difference between two images per batch and one is 0.3%, which I think is acceptable for quick testing.

I used a rather greedy padding, so the speed increase is only noticeable if run on multiple GPUs or on small images (`SCALE < 400`).

I can't get it to work on pascal_voc as `ratio_list` is not always correct.
